remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
title: EliteTools Documentation
description: Documentation for various tools
show_downloads: false
github.is_project_page: false
